import BodyComponent from "@/components/body/BodyComponent";
import Footer from "@/components/footer/Footer";
import Nav from "@/components/head/Nav";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>IDL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Nav />
        <BodyComponent />
        <Footer />
      </div>
    </>
  );
}
